name: ams
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  gallery_picker: ^0.5.1
  image_picker: ^1.0.8
  intl: ^0.19.0
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/AMS_LOGO1.png
    - assets/google.png
 
