// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZF8XRo7hvaCS0bivZks56k-SG25347A',
    appId: '1:304262283995:web:4cbc6eb0c22b81213a82fe',
    messagingSenderId: '304262283995',
    projectId: 'aammss-43bc1',
    authDomain: 'aammss-43bc1.firebaseapp.com',
    storageBucket: 'aammss-43bc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFvMt1mK9HHSejVxos8nocIufyCT-1K7s',
    appId: '1:304262283995:android:2f1db4615dd2ec663a82fe',
    messagingSenderId: '304262283995',
    projectId: 'aammss-43bc1',
    storageBucket: 'aammss-43bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgp8crUweDNEauhG-FWsuMuGQey2hK8hQ',
    appId: '1:304262283995:ios:6f202417f889c2323a82fe',
    messagingSenderId: '304262283995',
    projectId: 'aammss-43bc1',
    storageBucket: 'aammss-43bc1.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgp8crUweDNEauhG-FWsuMuGQey2hK8hQ',
    appId: '1:304262283995:ios:4cbe4e29769930983a82fe',
    messagingSenderId: '304262283995',
    projectId: 'aammss-43bc1',
    storageBucket: 'aammss-43bc1.appspot.com',
    iosBundleId: 'com.example.ams.RunnerTests',
  );
}
